### ISSUE TITLE
EINVALIDTAGNAME on installation

### ISSUE THREAD

**Issue by ZachKrae** [remigallego/react-native-use-sound#3]
When I try running npm install react-native-use-sound, I get this error:

```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^0.11.0": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by remigallego** [comment]
This has been fixed in [1.2.1](https://github.com/remigallego/react-native-use-sound/commit/331e2d89977806d614cf22cf8a8c6af00429321f). 

Thank you for opening the issue!
